# -*- mode: ruby -*-
# vi: set ft=ruby :

$start = <<SCRIPT
#!/usr/bin/env bash

export LC_ALL=C
export PYTHONUNBUFFERED=true

# install build dependencies
apt-get update
apt-get install -yy --no-install-recommends docker.io docker-compose \
  python3 python3-dev python3-pip python3-venv git gcc mongo-tools mongodb-clients curl \
  libxml2-dev libxslt-dev \
  libjpeg-dev zlib1g-dev \
  libmagic-dev \
  && rm -rf /var/lib/apt/lists/* 

cd /vagrant

ls

docker-compose up -d

export WEBPACK_SERVER_URL='http://10.0.2.2:8080/'
export ASSETS_URL='http://localhost:8080/'

# create venv
python3 -m venv env
. env/bin/activate

# update venv
python3 -m pip install -U 'pip<21.3' wheel setuptools

# install app
pip install -Ur requirements.txt

# init app
python manage.py create_user admin@localhost.com admin admin admin true
python manage.py elastic_init

# start app
honcho start -p 5050 &
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.network "forwarded_port", guest: 5050, host: 5050
  config.vm.network "forwarded_port", guest: 5150, host: 5150

  config.vm.provision :shell, inline: $start, run: "always"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
end
